Session tracking, apply_auto tweaks, security
Added session tracking to correctly kill daemon on logout.
More strict security filter on config and socket read to prevent injections.
Moved apply_auto relative position argument to variable. Now easier to replace --right-of with something else.

diff --git a/rerandr3 b/rerandr3
--- a/rerandr3
+++ b/rerandr3
@@ -40,6 +40,10 @@
 # 1366 * 768 = 1049088
 PIXEL_TRIGGER=1100000
 
+# which strategy to use when autostacking
+# (xrandr relative position options: --right-of, --left-of, --above, --below)
+AUTO_STRATEGY="--right-of"
+
 SOCKET="/tmp/rerandr3.fifo"
 DAEMON_LOG="$HOME/.rerandr3.log"
 UDEV_RULE_FILE="/etc/udev/rules.d/95-rerandr3-monitor-trigger.rules"
@@ -64,7 +68,7 @@ prepare_confdir(){
 }
 
 prepare_pipe(){
-	[ ! -p "$SOCKET" ] && mkfifo "$SOCKET"
+	[ ! -p "$SOCKET" ] && mkfifo -m 666 "$SOCKET"
 	[ "$(stat -c %a "$SOCKET")" != "666" ] && chmod 666 "$SOCKET"
 	[ ! -p "$SOCKET" -a "$(stat -c %a "$SOCKET")" != "666" ] && { echo "Could not prepare named pipe \"$SOCKET\"!" >&2 ; exit 1 ;}
 }
@@ -231,7 +235,7 @@ show_setup(){
 
 apply_saved(){
 	# sanitize args from config for security
-	SAVED_SETUP_ARGS="$(cat "$CONF_DIR/${SETUP_ID}.rerandr" | tr -d ';&')"
+	SAVED_SETUP_ARGS="$(cat "$CONF_DIR/${SETUP_ID}.rerandr" | sed 's/[^[:alnum:][:space:]\.,:_+-]//g')"
 	if [ "$SETUP_ARGS" = "$SAVED_SETUP_ARGS" ]
 	then
 		echo "Nothing to do."
@@ -267,30 +271,37 @@ apply_saved(){
 }
 
 apply_auto(){
-	# disable disconnected outputs preserving framebuffer size
-	# find some connected and enabled output
-	LAST_CONNECTED=
+	# disable disconnected and secondary outputs preserving framebuffer size
+	LAST_PRIMARY=
 	for OUTPUT_NUM in `seq 0 $(( ${#OUTPUT[@]} - 1 ))`
 	do
 		if [ "${STATUS[$OUTPUT_NUM]}" = "disconnected" -a -n "${MODE_CURRENT[$OUTPUT_NUM]}" ]
 		then
 			echo "Disabling disconnected output \"${OUTPUT[$OUTPUT_NUM]}\"..."
 			xrandr --fb "$DIMENSIONS" --output "${OUTPUT[$OUTPUT_NUM]}" --off
-		elif [ "${STATUS[$OUTPUT_NUM]}" = "connected" -a -n "${MODE_CURRENT[$OUTPUT_NUM]}" ]
+			MODE_CURRENT[$OUTPUT_NUM]=
+		elif [ "${STATUS[$OUTPUT_NUM]}" = "connected" -a -n "${MODE_CURRENT[$OUTPUT_NUM]}" -a "${ROLE[$OUTPUT_NUM]}" = "primary" ]
 		then
-			LAST_CONNECTED="${OUTPUT[$OUTPUT_NUM]}"
+			echo "found connected and active primary output ${OUTPUT[$OUTPUT_NUM]}"
+			LAST_PRIMARY="${OUTPUT[$OUTPUT_NUM]}"
 		fi
 	done
-	
+
 	# enable connected outputs stacking to the right
 	for OUTPUT_NUM in `seq 0 $(( ${#OUTPUT[@]} - 1 ))`
 	do
-		if [ "${STATUS[$OUTPUT_NUM]}" = "connected" -a -z "${MODE_CURRENT[$OUTPUT_NUM]}" ]
+		if [ "${STATUS[$OUTPUT_NUM]}" = "connected" ]
 		then
-			echo "Enabling connected output \"${OUTPUT[$OUTPUT_NUM]}\"..."
-			[ -n "$LAST_CONNECTED" ] && xrandr --output "${OUTPUT[$OUTPUT_NUM]}" --auto --right-of "$LAST_CONNECTED"
-			[ -z "$LAST_CONNECTED" ] && xrandr --output "${OUTPUT[$OUTPUT_NUM]}" --auto
-			LAST_CONNECTED="${OUTPUT[$OUTPUT_NUM]}"
+			if [ -z "$LAST_PRIMARY" ]
+			then
+				echo "Enabling connected output \"${OUTPUT[$OUTPUT_NUM]}\" as primary..."
+				xrandr --output "${OUTPUT[$OUTPUT_NUM]}" --auto --primary
+			elif [ -n "$LAST_PRIMARY" ]
+			then
+				echo "Enabling connected output \"${OUTPUT[$OUTPUT_NUM]}\"... as secondary"
+				xrandr --output "${OUTPUT[$OUTPUT_NUM]}" --auto "$AUTO_STRATEGY" "$LAST_PRIMARY"
+			fi
+			LAST_PRIMARY="${OUTPUT[$OUTPUT_NUM]}"
 		fi
 	done
 	applyhooks
@@ -310,49 +321,91 @@ apply_setup(){
 	fi
 }
 
+getsessionpid(){
+	# got this from fbpanel xlogout script, refined.
+	# find PID of session manager process to exit when it no longer exists
+
+	# get display number
+	DPY=${DISPLAY#*\:}
+	DPY=${DPY%%.*}
+
+	# get X pid
+	XPID=$(echo $(< /tmp/.X${DPY}-lock))
+
+	# get pid of xdm (or gdm, kdm, simple xinitrc, etc). usually it's parent of X
+	XDMPID=$(ps -o ppid --no-headers --pid=$XPID)
+
+	# recursivly find child of xdm that was started in home dir -
+	# it's user's session start up script
+		pid_scan(){
+			unset XDMCHILDREN
+			while [ $# != 0 ]; do
+				XDMCHILDREN="$XDMCHILDREN $(ps --no-headers -o pid --ppid=$1)"
+				shift
+			done
+			for pid in $XDMCHILDREN; do
+				if cwd=$(ls -al /proc/$pid/cwd 2>/dev/null); then
+					cwd=`sed 's/.*-> //' <<< $cwd`
+					[ "$cwd" = "$HOME" ] && echo $pid && return
+				fi
+			done
+			pids=$XDMCHILDREN
+			[ -n "$pids" ] && pid_scan $XDMCHILDREN;
+
+		}
+
+	SESSIONPID=`pid_scan $XDMPID`
+
+	[ -z "$SESSIONPID" ] && echo "No session parent found" >&2 && false
+	[ -n "$SESSIONPID" ] && echo $SESSIONPID
+}
+
+
 ##############################################
 #### window hooks
 ##############################################
 
 hooks() {
-# do things on every switch
-echo "Applying general hooks."
-#killall -USR1 conky
+	# do things on every switch
+	echo "Applying general hooks."
+	#killall -USR1 conky
 }
 
 smallhooks() {
-# do things if screen width is less than $PIXEL_TRIGGER
-echo "Applying small screen hooks."
-#wmctrl -xr Iceweasel	-b "add,maximized_horz,maximized_vert"
-#wmctrl -xr Icedove		-b "add,maximized_horz,maximized_vert"
-#wmctrl -xr Spacefm		-b "add,maximized_horz,maximized_vert"
+	# do things if screen area is less than $PIXEL_TRIGGER
+	echo "Applying small screen hooks."
+	#wmctrl -xr Iceweasel	-b "add,maximized_horz,maximized_vert"
+	#wmctrl -xr Icedove		-b "add,maximized_horz,maximized_vert"
+	#wmctrl -xr Spacefm		-b "add,maximized_horz,maximized_vert"
 }
 
 largehooks() {
-# do things if screen width is greater than $PIXEL_TRIGGER
-echo "Applying large screen hooks."
-#wmctrl -xr Iceweasel	-b "remove,maximized_vert,maximized_horz"
-#wmctrl -xr Icedove	-b "remove,maximized_vert,maximized_horz"
-#wmctrl -xr Spacefm	-b "remove,maximized_vert,maximized_horz"
-#wmctrl -xr Iceweasel	-e "0,-1,-1,1280,$HEIGHT"
-#wmctrl -xr Icedove	-e "0,-1,-1,1280,$HEIGHT"
-#wmctrl -xr Spacefm	-e "0,-1,-1,1280,$HEIGHT"
+	# do things if screen area is greater than $PIXEL_TRIGGER
+	echo "Applying large screen hooks."
+	#wmctrl -xr Iceweasel	-b "remove,maximized_vert,maximized_horz"
+	#wmctrl -xr Icedove	-b "remove,maximized_vert,maximized_horz"
+	#wmctrl -xr Spacefm	-b "remove,maximized_vert,maximized_horz"
+	#wmctrl -xr Iceweasel	-e "0,-1,-1,1280,$HEIGHT"
+	#wmctrl -xr Icedove	-e "0,-1,-1,1280,$HEIGHT"
+	#wmctrl -xr Spacefm	-e "0,-1,-1,1280,$HEIGHT"
 }
 
 applyhooks() {
-# calculate dimensions and apply hooks
-DIMENSIONS="$(xdpyinfo | grep dimensions | grep -o '[0-9]\+x[0-9]\+' | head -n 1)"
-WIDTH="$(echo "$DIMENSIONS" | cut -d x -f 1)"
-HEIGHT="$(echo "$DIMENSIONS" | cut -d x -f 2)"
-PIXELS="$(( $WIDTH * $HEIGHT ))"
-echo "Pixel quantity: $PIXELS"
-if [ "$PIXELS" -gt "$PIXEL_TRIGGER" ] ; then
-	hooks
-	largehooks
-else
-	hooks
-	smallhooks
-fi
+	# calculate dimensions and apply hooks
+	DIMENSIONS="$(xdpyinfo | grep dimensions | grep -o '[0-9]\+x[0-9]\+' | head -n 1)"
+	WIDTH="$(echo "$DIMENSIONS" | cut -d x -f 1)"
+	HEIGHT="$(echo "$DIMENSIONS" | cut -d x -f 2)"
+	PIXELS="$(( $WIDTH * $HEIGHT ))"
+	echo "Pixel quantity: $PIXELS"
+	if [ "$PIXELS" -gt "$PIXEL_TRIGGER" ] ; then
+		hooks
+		largehooks
+	else
+		hooks
+		smallhooks
+	fi
+	# hooks must not fail
+	true
 }
 
 check_udev(){
@@ -397,15 +450,29 @@ elif [ "$1" = "daemon" ]
 then
 	prepare_pipe 2>&1 | tee -a "$DAEMON_LOG"
 	check_udev | tee -a "$DAEMON_LOG"
-	# trap to kill all child processes of script
-	trap 'kill $(jobs -p) &>/dev/null ; echo deadbeef > $SOCKET' EXIT
-	trap 'kill $(jobs -p) &>/dev/null ; echo deadbeef > $SOCKET' SIGHUP
-	trap 'kill $(jobs -p) &>/dev/null ; echo deadbeef > $SOCKET' SIGINT
+
+	# clean pipes
+	cat /dev/null > "$SOCKET" &
+	cat "$SOCKET" | head -c 128 > /dev/null
+
 	"$0" restore 2>&1 | tee -a "$DAEMON_LOG"
+
+	# session tracking
+	getsessionpid
+	MAINPID="$$"
+	echo -e "Started daemon. PID: $MAINPID\nTracking session leader: PID $SESSIONPID" | tee -a "$DAEMON_LOG"
+	while true
+	do
+		kill -0 $SESSIONPID 2> /dev/null || { echo exit > "$SOCKET" ; exit 0 ; }
+		kill -0 $MAINPID 2> /dev/null || exit 0
+		sleep 3s
+	done &
+
+
 	while true
 	do
 		echo "Waiting for socket trigger..."
-		ACTION="$(cat "$SOCKET" | head -c 8)"
+		ACTION="$(cat "$SOCKET" | head -c 8 | sed 's/[^[:alpha:]_-]//g')"
 		if [ "$ACTION" = "save" ]
 		then
 			"$0" save
@@ -414,8 +481,12 @@ then
 		then
 			"$0" restore
 			ACTION=
+		elif [ "$ACTION" = "exit" ]
+		then
+			echo "Exiting..."
+			exit 0
 		else
-			echo "Unknown action."
+			echo "Unknown action \"$ACTION\"."
 			ACTION=
 			sleep 5s
 		fi
